# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2021-05-17 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateModified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=1000, null=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('dob', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('salary', models.FloatField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateModified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=1000, null=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=1000, null=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateModified', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=1000, null=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=1000, null=True)),
                ('qualificationName', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employeequalification',
            name='Qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Qualification'),
        ),
    ]
