# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2021-01-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210123_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='bookID',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
