# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2021-01-23 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='price',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='rating',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='ratingCount',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
