# Generated by Django 2.2 on 2021-01-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_ht',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
